
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gcache;

import java.util.Arrays;

public class App {

    public static void main(String ...args) {
        Cache cache = new QueueLRUCache(3);
        for(String item : Arrays.asList("a", "b", "p", "a", "p", "q")) {
            cache.insert(String.valueOf((int)item.charAt(0)), item);

        }
        System.out.println((String)cache.fetch("97"));
        System.out.println((String)cache.fetch("0"));
        for(Object o : cache.fetchAll()) {

            System.out.println((String)o);
        }
    }
}

